# Generated by Django 5.0.2 on 2024-04-21 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_is_verified_completed_vendorprofile_is_verification_completed'),
        ('events', '0002_alter_eventcategory_options_eventcategory_cat_image'),
        ('services', '0009_remove_requirement_event_remove_requirement_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('guest_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_advance_paid', models.BooleanField(default=False)),
                ('is_final_amount_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('LAUNCHED', 'LAUNCHED'), ('ASSIGNED', 'ASSIGNED'), ('WORK_IN_PROGRESS', 'WORK_IN_PROGRESS'), ('VERIFICATION_IN_PROGRESS', 'VERIFICATION_IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='LAUNCHED', max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.eventcategory')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_name', models.CharField(max_length=150)),
                ('has_sub', models.BooleanField(default=False)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_food', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=150)),
                ('area_of_decoration', models.CharField(blank=True, choices=[('STAGE', 'STAGE'), ('HALL', 'HALL'), ('BALL_ROOM', 'BALL_ROOM'), ('COURTYARD', 'COURTYARD'), ('ENTRANCE', 'ENTRANCE')], max_length=150, null=True)),
                ('construction_needed', models.BooleanField(default=False)),
                ('checklist', models.FileField(upload_to='event/requirement_files/')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.requirement')),
            ],
        ),
    ]
