# Generated by Django 5.0.2 on 2024-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_requirement_requirement_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
