# Generated by Django 5.0.2 on 2024-05-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_requirement_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/eventthumb/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.eventcategory'),
        ),
    ]
