# Generated by Django 5.0.2 on 2024-05-15 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_otherservices_unit_of_measurement'),
        ('events', '0006_event_cat_image_alter_event_event_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.clientprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vendorprofile'),
        ),
    ]
