# Generated by Django 5.0.2 on 2024-05-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_cat_image_event_thmbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='thmbnail',
            new_name='thumbnail',
        ),
    ]
