# Generated by Django 5.0.2 on 2024-05-15 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_thmbnail_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guest_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
