# Generated by Django 5.0.2 on 2024-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_stage',
            field=models.CharField(blank=True, choices=[('VENUE', 'LAUNCHED'), ('PENDING', 'PENDING'), ('ASSIGNED', 'ASSIGNED'), ('WORK_IN_PROGRESS', 'WORK_IN_PROGRESS'), ('VERIFICATION_IN_PROGRESS', 'VERIFICATION_IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('LAUNCHED', 'LAUNCHED'), ('PENDING', 'PENDING'), ('ASSIGNED', 'ASSIGNED'), ('WORK_IN_PROGRESS', 'WORK_IN_PROGRESS'), ('VERIFICATION_IN_PROGRESS', 'VERIFICATION_IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='LAUNCHED', max_length=200),
        ),
    ]
