# Generated by Django 5.0.2 on 2024-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_event_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='end_time',
            field=models.DateTimeField(default='2024-05-22T13:59'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
