# Generated by Django 5.0.2 on 2024-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_baseservices_rename_is_valid_service_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservices',
            name='normal_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
