# Generated by Django 5.0.2 on 2024-04-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_unit_of_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseServices',
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_of_measurement',
            field=models.CharField(choices=[('PERSON_COUNT', 'PERSON_COUNT'), ('COUNT', 'COUNT'), ('AREA(Sq_Ft)', 'AREA(Sq_Ft)')], default='PERSON_COUNT', max_length=100),
        ),
    ]
