# Generated by Django 5.0.2 on 2024-04-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_baseservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='parent',
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_name', models.CharField(max_length=150)),
                ('has_sub', models.BooleanField(default=False)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.event')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_food', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=150)),
                ('area_of_decoration', models.CharField(blank=True, choices=[('STAGE', 'STAGE'), ('HALL', 'HALL'), ('BALL_ROOM', 'BALL_ROOM'), ('COURTYARD', 'COURTYARD'), ('ENTRANCE', 'ENTRANCE')], max_length=150, null=True)),
                ('construction_needed', models.BooleanField(default=False)),
                ('checklist', models.FileField(upload_to='event/requirement_files/')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.requirement')),
            ],
        ),
    ]
