# Generated by Django 5.0.2 on 2024-04-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_event_remove_service_parent_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='event',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='service',
        ),
        migrations.RemoveField(
            model_name='requirementdetails',
            name='requirement',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='RequirementDetails',
        ),
    ]
