# Generated by Django 5.0.2 on 2024-04-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_requirement_event_remove_requirement_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost_per_unit',
        ),
    ]
