# Generated by Django 5.0.2 on 2024-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_service_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, choices=[('CATERING', 'CATERING'), ('DECORATION', 'DECORATION'), ('OTHERS', 'OTHERS')], max_length=150, null=True),
        ),
    ]
