# Generated by Django 5.0.2 on 2024-02-26 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor/logo/')),
                ('website', models.CharField(max_length=100)),
                ('service_capacity', models.CharField(choices=[('LESS THAN 1L', 'LESS THAN 1L'), ('1L-10L', '1L-10L'), ('10L -25L', '10L -25L'), ('GREATER THAN 25L', 'GREATER THAN 25L')], max_length=100)),
                ('specialised_on', models.ManyToManyField(related_name='services_specialised_on', to='services.service')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=50)),
                ('unit_of_measurement', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childservice', to='accounts.otherservices')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendorprofile')),
            ],
        ),
    ]
