# Generated by Django 5.0.2 on 2024-04-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherservices',
            name='unit_of_measurement',
            field=models.CharField(choices=[('PERSON_COUNT', 'PERSON_COUNT'), ('COUNT', 'COUNT'), ('AREA(Sq_Ft)', 'AREA(Sq_Ft)')], default='PERSON_COUNT', max_length=100),
        ),
    ]
