# Generated by Django 5.0.2 on 2024-04-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otherservices_unit_of_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherservices',
            name='is_valid',
        ),
    ]
