# Generated by Django 5.0.2 on 2024-04-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vendorprofile_is_verified_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='is_verified_completed',
            new_name='is_verification_completed',
        ),
    ]
