# Generated by Django 5.0.2 on 2024-04-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_is_verified_completed_vendorprofile_is_verification_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherservices',
            name='parent',
        ),
    ]
