# Generated by Django 5.0.2 on 2024-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_otherservices_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservices',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otherservices',
            name='other_unit_of_measurement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherservices',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='service/thumbnail'),
        ),
        migrations.AlterField(
            model_name='otherservices',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
