# Generated by Django 5.0.2 on 2024-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_otherservices_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherservices',
            name='unit_of_measurement',
            field=models.CharField(choices=[('OTHER_UNIT', 'OTHER_UNIT'), ('PERSON_COUNT', 'PERSON_COUNT'), ('COUNT', 'COUNT'), ('AREA(Sq_Ft)', 'AREA(Sq_Ft)')], default='PERSON_COUNT', max_length=100),
        ),
    ]
