# Generated by Django 5.0.2 on 2024-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('add_line_1', models.TextField()),
                ('add_line_2', models.TextField()),
                ('lat_long', models.TextField()),
                ('street', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('venue_type', models.CharField(choices=[('OUTDOOR', 'OUTDOOR'), ('INDOOR', 'INDOOR')], max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
