# Generated by Django 5.0.2 on 2024-05-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='add_line_1',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='add_line_2',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='pincode',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='street',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('OUTDOOR', 'OUTDOOR'), ('INDOOR', 'INDOOR')], db_index=True, max_length=150),
        ),
    ]
