# Generated by Django 5.0.2 on 2024-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0004_venue_full_address_alter_venue_add_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='management_company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='rental_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='reservation_status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('BOOKED', 'BOOKED'), ('UNAVAILABLE', 'UNAVAILABLE')], db_index=True, default='AVAILABLE', max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('OUTDOOR', 'OUTDOOR'), ('INDOOR', 'INDOOR'), ('RESORT', 'RESORT'), ('AUDITORIUM', 'AUDITORIUM')], db_index=True, max_length=150),
        ),
    ]
