# Generated by Django 5.0.2 on 2024-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0005_venue_capacity_venue_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='lat_long',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
