# Generated by Django 5.0.2 on 2024-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0007_amenities_venue_amenities_venueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='venue/thumbnail'),
        ),
    ]
